name: online_sheets_server
description: A sample command-line application.
version: 1.0.0

environment:
  sdk: '>=2.19.6 <3.0.0'

dependencies:
  shelf: ^1.4.1
  shelf_web_socket: ^1.0.4
  web_socket_channel: ^2.4.0

dev_dependencies:
  lints: ^2.0.1
  test: ^1.24.2
